### ISSUE TITLE
UnmarshalFromJSONMap doesn't support int/int64

### ISSUE THREAD

**Issue by tmm1** [PerimeterX/marshmallow#13]
Hi, thanks for sharing this great library.

I was surprised that `UnmarshalFromJSONMap` only supports float64. Are you open to a patch to add support for int/int64?

**Comment by tmm1** [comment]
My mistake, I see that json.Unmarshal always returns numbers as `float64`

**Comment by avivpxi** [comment]
Exactly, although there's no performance impact of supporting all numeric types instead of just float64
