### ISSUE TITLE
Support any types that has UnmarshalJSON/MarshalJSON method

### ISSUE THREAD

**Issue by knoguchi** [PerimeterX/marshmallow#22]
I wonder if you could support non-primitive types  such as time.Time just like the standard json.Unmarshal json.Marshal does.   I only need it when such types implemented UnmarshalJSON/MarshalJSON methods.

**Comment by avivpxi** [comment]
Sure! This is already supported. Any type implementing custom JSON unmarshaler will be respected as you expect.
[Example](https://go.dev/play/p/At13rv_HBal)

Let us know if it works for you, or you need anything else 🙏

**Comment by avivpxi** [comment]
@knoguchi making sure you've seen this one before I'm closing the issue

**Comment by knoguchi** [comment]
Thank you. I have one example that I can't figure out.  I will post it shortly.

**Comment by avivpxi** [comment]
@knoguchi any news here?

**Comment by avivpxi** [comment]
Closing due to no response
